### ISSUE TITLE
Sync 모듈과 FSM 연결

### ISSUE THREAD

**Issue by Hwan007** [Team-Omoshiroi/Omoshiroi#86]
# 설명(Description)
- 파일럿 Sync 모듈의 호출을 FSM에서 조건 하에 호출 하는 것으로 수정.
- 클론 Sync 모듈의 호출을 Input으로서 Movement 및 Animation Controller FSM 작성.

- Sync 모듈과 캐릭터를 연결

# To Do List
# 채이환
- [x] 파일럿 Sync와 FSM 연결
- [x] 클론 Sync용 Movement 및 Animation Controller FSM 작성
- [x] 공격을 받았을 때 받은 충격에 의한 이동 처리 문제(입력이 없는 경우에는 FSM에서 패킷을 보내지 않는다.)
=> 이를 AddImpact 했을 때 Idle인 경우에만 문제가 되므로, Idle에서 AddImpact가 되면 패킷을 보내도록 수정할 예정.
Character Controller의 velocity.sarMagnitude > 0 을 체크해서 IdleState에서 업데이트 하도록 수정.
- [x] #243
=> 해당 투사체가 파괴된 것을 서버로 송신하기로 함.
1번안) 서버가 투사체 ID를 생성해 송신
2번안) 캐릭터가 투사체 ID를 생성해 송신
- [x] #189
=> 튜터님께 도움을 좀 받아야 될 듯. 시간을 어떻게 맞추어야 하는지 알아야 한다. DateTime.now를 사용하여 시간을 보내는 것은 어떠한가.
- [x] 걷다가 구르면 멈추지 않는다.
- [x] 움직임이 조금 끊기는게 있다. 인터넷 속도는 충분히 빠르다.
=> 이전 프레임의 속도를 전달하기 때문에 발생하는 것으로 예상됨. (Character Controller의 velocity는 physics 영역에서 계산되는 것으로 추론됨) 적용하고 부드러운 것을 확인.
- [x] 움직임 이외에 이벤트 호출이 되지 않는다. => 구르기에 움직임이 호출이 된다.
- [x] 조준 중에 다른 BaseLayer에서 Run으로 가면 이속이 다시 복구되는 것을 수정할 필요가 있음.
=> 달리기 버튼에 대한 정보를 유지하는 것으로 전면수정
- [x] 콤보 공격에 대한 애니메이션 동기화 정보를 수정해야 될 듯.
=> ComboIndex에 대한 전달이 필요함
- [x] 애니메이션 동기화는 시작과 끝만 제대로 하면 된다.
=> animTime 패킷 정보를 삭제

# 배인호
- [x] 패킷에 속도에 대한 정보를 담을 수 있도록 수정
- [x] 공격, 회피, 조준, 낙하에 대한 패킷을 보낼 수 있도록 수정
- [x] Protocol.proto 수정
- [x] 업데이트한 Protocol에 맞게 구조 변경 및 변수명 변경
- [x] Move Packet Sync 테스트
- [x] message 변수명 변경하기 (내용에 대한 설명이 부족한 변수명으로, 다른 이들이 확실히 인지하기 위함)

**Comment by Hwan007** [comment]
공격, 회피, 조준, 낙하에 대한 애니메이션 제어를 위한 NormalizeTime이 필요합니다.
해당 내용을 보낼 수 있게 패킷을 수정하였으면 합니다.
@cutlake2000 
```
// public class BaseState : IState
    protected float GetNormalizedTime(Animator animator, int layer, string tag)
    {
        AnimatorStateInfo currentInfo = animator.GetCurrentAnimatorStateInfo(layer);
        AnimatorStateInfo nextInfo = animator.GetNextAnimatorStateInfo(layer);
        if (animator.IsInTransition(layer) && nextInfo.IsTag(tag))
        {
            return nextInfo.normalizedTime;
        }
        else if (!animator.IsInTransition(layer) && currentInfo.IsTag(tag))
        {
            return currentInfo.normalizedTime;
        }
        else
        {
            return 0f;
        }
    }
```

```
//public class CloneBaseState : IState
    public virtual void SetAnimation(Animator animator, int layer, float normalizeTime)
    {
        var state = animator.GetCurrentAnimatorStateInfo(layer);
        animator.Play(state.fullPathHash, layer, normalizeTime);
    }
```

**Comment by Hwan007** [comment]
지금 공격을 받았을 때 받은 충격에 의한 이동이 처리되지 않는 문제가 있음

**Comment by cutlake2000** [comment]
# S_Aim과 S_AimHandler가 정상적으로 호출되지 않는 문제

S_Move과 S_Battle 패킷은 정상적으로 PacketQueue에 담기는 것을 확인하였음 -> S_Aim 패킷이 PacketQueue에 담기지 않고 있음
